### PR TITLE
pyspark 3.2.1

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Requirements:
- https://github.com/apache/spark/blob/v3.2.1/python/setup.py

Actions:
1. Update `license` file
2. Remove `noarch python`
3. Skip `s390x` because of `pyarrow` isn't available
4. Update runtime pinnings
5. Update `test/imports`
6. Fix `home` url
7. Update `summary`

### CODE REVIEW

**Comment by aniedzielaAnaconda** [comment]
Need to add licenses from: https://github.com/apache/spark/tree/v3.2.1/licenses

**Comment by marcoesters** [comment]
Is there a reason we don't update to the newest version, or at least not to the latest patch version that's compatible with 3.2.1?

It would be great if you could post a change log in the future to make it easier to see why this wasn't done.

**Comment by skupr-anaconda** [comment]
> Is there a reason we don't update to the newest version, or at least not to the latest patch version that's compatible with 3.2.1?
> 
> It would be great if you could post a change log in the future to make it easier to see why this wasn't done.

The request to update this version is https://anaconda.atlassian.net/browse/PKG-740. As of today, there is no additional info on why exactly this version was required.

**Review by marcoesters — APPROVED** [review]
LGTM then

**Pull request merged**
